#ifndef NONLINEARBOUNDARYVALUEPROBLEMODE_H
#define NONLINEARBOUNDARYVALUEPROBLEMODE_H

#include "bvp.h"

class MINIMUMSHARED_EXPORT NonLinearBoundaryValueProblemODE : protected BoundaryValueProblemODE
{
};

#endif // NONLINEARBOUNDARYVALUEPROBLEMODE_H
